# Initialisation

In [4]:
import os 
import sys
import pandas as pd
import numpy as np
import seaborn as sns

# Lecture du premier dataFrame

In [2]:
bpopu_2013_df = pd.read_csv("bilan_popu_2013.csv")

In [3]:
bpopu_2013_df.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,31731.688,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."
1,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,53767.396,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."
2,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,2918.978,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."
3,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,38338.562,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."
4,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,81265.139,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."

# Reorganisation du dataFrame bpopu_2013_df

In [4]:
bpopu_2013_df = bpopu_2013_df[['Zone','Valeur']].copy()
bpopu_2013_df.head()

             Zone     Valeur
0     Afghanistan  31731.688
1  Afrique du Sud  53767.396
2         Albanie   2918.978
3         Algérie  38338.562
4       Allemagne  81265.139

# Q1

In [5]:
bpopu_2013_df.columns=["Pays", "Population"]
bpopu_2013_df['Population']*=1000
pop_total_2013 = bpopu_2013_df['Population'].sum()

# Creation table_pivot bilan alimentaire

In [6]:
# Import des librairies
import numpy as np
import pandas as pd
import seaborn as sns


# Import des données des bilans alimentaires
veg = pd.read_csv("vegetal.csv")
ani = pd.read_csv("animal.csv")

# Ajout de la variable origin
ani["origin"] = "animal"
veg["origin"] = "vegetal"

# On regroupe veg et ani en un unique dataframe, via une union
temp = ani.append(veg)

# Suppression de ani et veg
del ani, veg

# Transformation de temp en table pivot
data = temp.pivot_table(index=["Pays","Produit","origin"],
                        columns = ["Élément"], values=["Valeur"], aggfunc=sum)

data.columns = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité alimentaire (Kcal/personne/jour)', 
                'Disponibilité alimentaire en quantité (kg/personne/an)', 
                'Disponibilité de matière grasse en quantité (g/personne/jour)', 
                'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']

data = data.reset_index()

colonnes_mult = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité intérieure', 'Exportations - Quantité', 
                 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 'Semences', 'Traitement', 'Variation de stock']
for elt in colonnes_mult:
    data[elt] *= 1000000

data.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animal,NaN,NaN,5.0,1.72,0.20,0.77,53000000.0,NaN,NaN,53000000.0,NaN,53000000.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetal,NaN,NaN,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetal,NaN,NaN,1.0,0.06,0.01,0.03,2000000.0,NaN,2000000.0,2000000.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetal,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetal,NaN,NaN,4.0,2.70,0.02,0.05,82000000.0,NaN,82000000.0,82000000.0,NaN,NaN,NaN,NaN,NaN

### Remplacement des NaN par une valeur nul (0)

In [7]:
data = data.fillna(value={"Aliments pour animaux":0,
                          "Autres Utilisations":0, 
                          "Disponibilité alimentaire (Kcal/personne/jour)":0, 
                          "Disponibilité alimentaire en quantité (kg/personne/an)":0,
                          "Disponibilité de matière grasse en quantité (g/personne/jour)":0, 
                          "Disponibilité de protéines en quantité (g/personne/jour)":0, 
                          "Exportations - Quantité":0, 
                          "Importations - Quantité":0, 
                          "Pertes":0, 
                          "Production":0, 
                          "Semences":0, 
                          "Traitement":0, 
                          "Variation de stock":0})

In [8]:
len(data.Produit.unique())
data.Produit.unique()

array(['Abats Comestible', 'Agrumes, Autres', 'Aliments pour enfants',
       'Ananas', 'Bananes', 'Beurre, Ghee', 'Bière', 'Blé',
       'Boissons Alcooliques', 'Café', 'Coco (Incl Coprah)', 'Crème',
       'Céréales, Autres', 'Dattes', 'Edulcorants Autres',
       'Feve de Cacao', 'Fruits, Autres', 'Graines de coton',
       'Graines de tournesol', 'Graisses Animales Crue',
       'Huil Plantes Oleif Autr', 'Huile Graines de Coton',
       "Huile d'Arachide", "Huile d'Olive", 'Huile de Colza&Moutarde',
       'Huile de Palme', 'Huile de Soja', 'Huile de Sésame',
       'Huile de Tournesol', 'Lait - Excl Beurre', 'Légumes, Autres',
       'Légumineuses Autres', 'Maïs', 'Miel', 'Millet', 'Miscellanees',
       'Noix', 'Oeufs', 'Olives', 'Oranges, Mandarines', 'Orge',
       'Plantes Oleiferes, Autre', 'Poissons Eau Douce', 'Poivre',
       'Pommes', 'Pommes de Terre', 'Raisin', 'Riz (Eq Blanchi)',
       'Sucre Eq Brut', 'Sucre, betterave', 'Sucre, canne', 'Sésame',
       'Thé', 'Tomates', "Viande d'Ovins/Caprins", 'Viande de Bovins',
       'Viande de Volailles', 'Viande, Autre', 'Vin', 'Épices, Autres',
       'Alcool, non Comestible', 'Animaux Aquatiques Autre',
       'Arachides Decortiquees', 'Avoine', 'Bananes plantains',
       'Boissons Fermentés', 'Cephalopodes', 'Citrons & Limes',
       'Crustacés', 'Girofles', 'Graines Colza/Moutarde', 'Haricots',
       'Huile de Coco', 'Huile de Germe de Maïs', 'Huile de Palmistes',
       'Huiles de Foie de Poisso', 'Huiles de Poissons', 'Ignames',
       'Manioc', 'Mollusques, Autres', 'Oignons', 'Palmistes',
       'Pamplemousse', 'Patates douces', 'Perciform', 'Piments',
       'Plantes Aquatiques', 'Pois', 'Poissons Marins, Autres',
       'Poissons Pelagiques', 'Racines, Nda', 'Seigle', 'Soja', 'Sorgho',
       'Viande de Suides', 'Huile de Son de Riz', 'Sucre non centrifugé',
       'Viande de Anim Aquatiq'], dtype=object)

In [9]:
data.head(80)

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animal,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Afrique du Sud,Café,vegetal,0.0,0.0,1.0,0.93,0.00,0.06,49000000.0,15000000.0,64000000.0,49000000.0,0.0,0.0,0.0,0.0,0.0
76,Afrique du Sud,Cephalopodes,animal,0.0,0.0,0.0,0.12,0.00,0.05,7000000.0,5000000.0,9000000.0,7000000.0,0.0,3000000.0,0.0,0.0,0.0
77,Afrique du Sud,Citrons & Limes,vegetal,0.0,0.0,0.0,0.38,0.00,0.00,33000000.0,253000000.0,2000000.0,20000000.0,13000000.0,257000000.0,0.0,0.0,27000000.0
78,Afrique du Sud,Coco (Incl Coprah),vegetal,0.0,0.0,2.0,0.46,0.16,0.02,24000000.0,1000000.0,25000000.0,24000000.0,0.0,0.0,0.0,0.0,0.0
79,Afrique du Sud,Crustacés,animal,0.0,0.0,0.0,0.42,0.00,0.10,22000000.0,4000000.0,24000000.0,22000000.0,0.0,3000000.0,0.0,0.0,0.0

# Q2

Disponibilité intérieure = Production + Importations - Exportations + Variation des stocks = Nourriture + Aliments pour animaux + Semences + Pertes + Traitement + Autres Utilisations

# Q3

## Merge du dataFrame data et bpopu_2013_df

In [10]:
merge = pd.merge(data, bpopu_2013_df)

In [11]:
merge

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Population
0,Afghanistan,Abats Comestible,animal,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0,31731688.0
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,31731688.0
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,31731688.0
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31731688.0
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,31731688.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15223,Îles Salomon,Viande de Suides,animal,0.0,0.0,45.0,4.70,4.28,1.41,3000000.0,0.0,0.0,3000000.0,0.0,2000000.0,0.0,0.0,0.0,563513.0
15224,Îles Salomon,Viande de Volailles,animal,0.0,0.0,11.0,3.34,0.69,1.14,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,563513.0
15225,Îles Salomon,"Viande, Autre",animal,0.0,0.0,0.0,0.06,0.00,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,563513.0
15226,Îles Salomon,Vin,vegetal,0.0,0.0,0.0,0.07,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,563513.0
15227,Îles Salomon,"Épices, Autres",vegetal,0.0,0.0,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,563513.0

## Reorganisation des colonnes

In [12]:
merge = merge[['Pays', 'Population', 'Produit', 'Nourriture', 'origin', 'Disponibilité alimentaire (Kcal/personne/jour)',
               'Disponibilité de protéines en quantité (g/personne/jour)']].copy()

## Ajout de deux nouvelles colonnes plus les valeurs attendues

In [13]:
merge['Dispo Alim totale(Kcal)'] = merge['Population'] * merge['Disponibilité alimentaire (Kcal/personne/jour)'] * 365
merge.head()

,Pays,Population,Produit,Nourriture,origin,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Dispo Alim totale(Kcal)
0,Afghanistan,31731688.0,Abats Comestible,53000000.0,animal,5.0,0.77,5.791033e+10
1,Afghanistan,31731688.0,"Agrumes, Autres",39000000.0,vegetal,1.0,0.02,1.158207e+10
2,Afghanistan,31731688.0,Aliments pour enfants,2000000.0,vegetal,1.0,0.03,1.158207e+10
3,Afghanistan,31731688.0,Ananas,0.0,vegetal,0.0,0.00,0.000000e+00
4,Afghanistan,31731688.0,Bananes,82000000.0,vegetal,4.0,0.05,4.632826e+10

In [14]:
merge['Dispo Proteines Totale (g)'] = merge['Population'] * merge['Disponibilité de protéines en quantité (g/personne/jour)'] * 365
merge.head()

,Pays,Population,Produit,Nourriture,origin,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Dispo Alim totale(Kcal),Dispo Proteines Totale (g)
0,Afghanistan,31731688.0,Abats Comestible,53000000.0,animal,5.0,0.77,5.791033e+10,8.918191e+09
1,Afghanistan,31731688.0,"Agrumes, Autres",39000000.0,vegetal,1.0,0.02,1.158207e+10,2.316413e+08
2,Afghanistan,31731688.0,Aliments pour enfants,2000000.0,vegetal,1.0,0.03,1.158207e+10,3.474620e+08
3,Afghanistan,31731688.0,Ananas,0.0,vegetal,0.0,0.00,0.000000e+00,0.000000e+00
4,Afghanistan,31731688.0,Bananes,82000000.0,vegetal,4.0,0.05,4.632826e+10,5.791033e+08

## Changement de nom du dataFrame en "tableau"

In [15]:
tableau = merge.copy()
tableau.head()

,Pays,Population,Produit,Nourriture,origin,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Dispo Alim totale(Kcal),Dispo Proteines Totale (g)
0,Afghanistan,31731688.0,Abats Comestible,53000000.0,animal,5.0,0.77,5.791033e+10,8.918191e+09
1,Afghanistan,31731688.0,"Agrumes, Autres",39000000.0,vegetal,1.0,0.02,1.158207e+10,2.316413e+08
2,Afghanistan,31731688.0,Aliments pour enfants,2000000.0,vegetal,1.0,0.03,1.158207e+10,3.474620e+08
3,Afghanistan,31731688.0,Ananas,0.0,vegetal,0.0,0.00,0.000000e+00,0.000000e+00
4,Afghanistan,31731688.0,Bananes,82000000.0,vegetal,4.0,0.05,4.632826e+10,5.791033e+08

# Q4

## Ajout de la colonne Ratio avec les valeurs attendues

In [16]:
tableau['Ratio(Kcal/Kg)'] = tableau['Dispo Alim totale(Kcal)'] / tableau['Nourriture']
tableau['Ratio(g prot/Kg)'] = tableau['Dispo Proteines Totale (g)'] / tableau['Nourriture']
tableau.head()

,Pays,Population,Produit,Nourriture,origin,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Dispo Alim totale(Kcal),Dispo Proteines Totale (g),Ratio(Kcal/Kg),Ratio(g prot/Kg)
0,Afghanistan,31731688.0,Abats Comestible,53000000.0,animal,5.0,0.77,5.791033e+10,8.918191e+09,1092.647747,168.267753
1,Afghanistan,31731688.0,"Agrumes, Autres",39000000.0,vegetal,1.0,0.02,1.158207e+10,2.316413e+08,296.976054,5.939521
2,Afghanistan,31731688.0,Aliments pour enfants,2000000.0,vegetal,1.0,0.03,1.158207e+10,3.474620e+08,5791.033060,173.730992
3,Afghanistan,31731688.0,Ananas,0.0,vegetal,0.0,0.00,0.000000e+00,0.000000e+00,NaN,NaN
4,Afghanistan,31731688.0,Bananes,82000000.0,vegetal,4.0,0.05,4.632826e+10,5.791033e+08,564.978835,7.062235

In [17]:
tableau = tableau.replace([np.inf, -np.inf], np.nan)
tableau = tableau.replace(0, np.nan)
tableau = tableau.groupby('Produit').mean()
tableau = tableau.reset_index()

# Q5

In [18]:
tableau = tableau.fillna(0)
tableau.head()

,Produit,Population,Nourriture,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Dispo Alim totale(Kcal),Dispo Proteines Totale (g),Ratio(Kcal/Kg),Ratio(g prot/Kg)
0,Abats Comestible,3.312910e+07,6.768790e+07,8.071006,1.248176,7.082837e+10,1.124111e+10,1140.563269,177.166342
1,"Agrumes, Autres",3.502706e+07,6.881818e+07,3.263158,0.047111,3.827659e+10,7.060956e+08,254.349494,4.516521
2,"Alcool, non Comestible",3.441317e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
3,Aliments pour enfants,3.351297e+07,6.847826e+06,5.635514,0.194806,2.122817e+10,7.539141e+08,3712.156093,149.897167
4,Ananas,3.350581e+07,1.349929e+08,5.237705,0.043524,5.322980e+10,4.699007e+08,446.795448,3.113789

In [19]:
tableau = tableau[['Produit', 'Ratio(Kcal/Kg)', 'Ratio(g prot/Kg)']]
tableau.head()

                  Produit  Ratio(Kcal/Kg)  Ratio(g prot/Kg)
0        Abats Comestible     1140.563269        177.166342
1         Agrumes, Autres      254.349494          4.516521
2  Alcool, non Comestible        0.000000          0.000000
3   Aliments pour enfants     3712.156093        149.897167
4                  Ananas      446.795448          3.113789

# Q6

In [20]:
vegetals = data.loc[data['origin']=='vegetal']
vegetals.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0
6,Afghanistan,Bière,vegetal,0.0,0.0,0.0,0.09,0.00,0.00,3000000.0,0.0,3000000.0,3000000.0,0.0,0.0,0.0,0.0,0.0

In [21]:
veg_table = pd.merge(vegetals, tableau, on='Produit', how='inner')
veg_table.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Ratio(Kcal/Kg),Ratio(g prot/Kg)
0,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,254.349494,4.516521
1,Afrique du Sud,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.14,0.00,0.00,8000000.0,3000000.0,0.0,8000000.0,1000000.0,11000000.0,0.0,0.0,0.0,254.349494,4.516521
2,Albanie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.24,0.00,0.00,1000000.0,0.0,1000000.0,1000000.0,0.0,0.0,0.0,0.0,0.0,254.349494,4.516521
3,Algérie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.23,0.00,0.00,9000000.0,0.0,9000000.0,9000000.0,0.0,1000000.0,0.0,0.0,0.0,254.349494,4.516521
4,Allemagne,"Agrumes, Autres",vegetal,0.0,0.0,1.0,2.27,0.00,0.01,188000000.0,39000000.0,227000000.0,188000000.0,0.0,0.0,0.0,0.0,0.0,254.349494,4.516521

In [22]:
veg_table['Disponibilité intérieure Kcal'] = veg_table['Disponibilité intérieure'] * veg_table['Ratio(Kcal/Kg)']
veg_table['Disponibilité intérieure g Prot'] = veg_table['Disponibilité intérieure'] * veg_table['Ratio(g prot/Kg)']
veg_table.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Ratio(Kcal/Kg),Ratio(g prot/Kg),Disponibilité intérieure Kcal,Disponibilité intérieure g Prot
0,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,...,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,254.349494,4.516521,1.042833e+10,1.851774e+08
1,Afrique du Sud,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.14,0.00,0.00,8000000.0,...,8000000.0,1000000.0,11000000.0,0.0,0.0,0.0,254.349494,4.516521,2.034796e+09,3.613217e+07
2,Albanie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.24,0.00,0.00,1000000.0,...,1000000.0,0.0,0.0,0.0,0.0,0.0,254.349494,4.516521,2.543495e+08,4.516521e+06
3,Algérie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.23,0.00,0.00,9000000.0,...,9000000.0,0.0,1000000.0,0.0,0.0,0.0,254.349494,4.516521,2.289145e+09,4.064869e+07
4,Allemagne,"Agrumes, Autres",vegetal,0.0,0.0,1.0,2.27,0.00,0.01,188000000.0,...,188000000.0,0.0,0.0,0.0,0.0,0.0,254.349494,4.516521,4.781770e+10,8.491060e+08

In [23]:
print("Dispo interrieur mondiale en Kcal : ", veg_table['Disponibilité intérieure Kcal'].sum())
print("Dispo interrieur mondiale en g Prot : ", veg_table['Disponibilité intérieure g Prot'].sum())

Dispo interrieur mondiale en Kcal :  1.3908919223208508e+16
Dispo interrieur mondiale en g Prot :  352219306494508.75

# Q7

In [24]:
pop_total_2013

7213211612.0

In [25]:
besoin_Kcal = 2350 * 365

In [26]:
print("on peut nourir : ", veg_table['Disponibilité intérieure Kcal'].sum() / besoin_Kcal)
nourrir_HU_kcal = veg_table['Disponibilité intérieure Kcal'].sum() / besoin_Kcal

on peut nourir :  16215586386.719334

In [27]:
nourrir_HU_kcal_prc = (nourrir_HU_kcal / pop_total_2013) * 100
nourrir_HU_kcal_prc

224.8039744147095

###  224.80 % , soit plus de 2 fois la population mondiale

In [28]:
besoin_gprot = (0.85*70) * 365

In [29]:
print("on peut nourir : ", veg_table['Disponibilité intérieure g Prot'].sum() / besoin_gprot)
nourrir_HU_gprot = veg_table['Disponibilité intérieure g Prot'].sum() / besoin_gprot

on peut nourir :  16218225232.854092

In [30]:
nourrir_HU_gprot_prc = (nourrir_HU_gprot / pop_total_2013) * 100
nourrir_HU_gprot_prc

224.84055792669696

### 224.84 % soit la population mondiale, soit 2 fois la population mondiale

# Q8

In [31]:
print(veg_table['Aliments pour animaux'].sum())
print(veg_table['Nourriture'].sum())
print(veg_table['Pertes'].sum())

1196619000000.0
3692542000000.0
429768000000.0

In [32]:
veg_table['Disponibilité Food/Feed/Waste Kcal'] = (veg_table['Aliments pour animaux'] + veg_table['Nourriture'] + veg_table['Pertes']) * veg_table['Ratio(Kcal/Kg)']
veg_table['Disponibilité Food/Feed/Waste g Prot'] = (veg_table['Aliments pour animaux'] + veg_table['Nourriture'] + veg_table['Pertes']) * veg_table['Ratio(g prot/Kg)']
veg_table.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Production,Semences,Traitement,Variation de stock,Ratio(Kcal/Kg),Ratio(g prot/Kg),Disponibilité intérieure Kcal,Disponibilité intérieure g Prot,Disponibilité Food/Feed/Waste Kcal,Disponibilité Food/Feed/Waste g Prot
0,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,...,3000000.0,0.0,0.0,0.0,254.349494,4.516521,1.042833e+10,1.851774e+08,1.042833e+10,1.851774e+08
1,Afrique du Sud,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.14,0.00,0.00,8000000.0,...,11000000.0,0.0,0.0,0.0,254.349494,4.516521,2.034796e+09,3.613217e+07,2.289145e+09,4.064869e+07
2,Albanie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.24,0.00,0.00,1000000.0,...,0.0,0.0,0.0,0.0,254.349494,4.516521,2.543495e+08,4.516521e+06,2.543495e+08,4.516521e+06
3,Algérie,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.23,0.00,0.00,9000000.0,...,1000000.0,0.0,0.0,0.0,254.349494,4.516521,2.289145e+09,4.064869e+07,2.289145e+09,4.064869e+07
4,Allemagne,"Agrumes, Autres",vegetal,0.0,0.0,1.0,2.27,0.00,0.01,188000000.0,...,0.0,0.0,0.0,0.0,254.349494,4.516521,4.781770e+10,8.491060e+08,4.781770e+10,8.491060e+08

In [33]:
print("Dispo Food/Feed/Waste mondiale en Kcal : ", veg_table['Disponibilité Food/Feed/Waste Kcal'].sum())
print("Dispo Food/Feed/Waste mondiale en g Prot : ", veg_table['Disponibilité Food/Feed/Waste g Prot'].sum())

Dispo Food/Feed/Waste mondiale en Kcal :  9492160350318168.0
Dispo Food/Feed/Waste mondiale en g Prot :  213608317485979.75

In [34]:
print("avec Food/Feed/Waste Kcal on peut nourrir : ", veg_table['Disponibilité Food/Feed/Waste Kcal'].sum() / besoin_Kcal)
print("avec Food/Feed/Waste g Prot on peut nourrir : ", veg_table['Disponibilité Food/Feed/Waste g Prot'].sum() / besoin_gprot)
nourrir_HU_FFW_kcal = veg_table['Disponibilité Food/Feed/Waste Kcal'].sum() / besoin_Kcal
nourrir_HU_FFW_gprot = veg_table['Disponibilité Food/Feed/Waste g Prot'].sum() / besoin_gprot

avec Food/Feed/Waste Kcal on peut nourrir :  11066348411.912758
avec Food/Feed/Waste g Prot on peut nourrir :  9835769194.703798

In [35]:
nourrir_HU_FFW_kcal_prc = (nourrir_HU_FFW_kcal / pop_total_2013) * 100
nourrir_HU_FFW_gprot_prc = (nourrir_HU_FFW_gprot / pop_total_2013) * 100

In [36]:
nourrir_HU_FFW_kcal_prc

153.41777015806144

### 153,4 % de la population mondiale pourrait être nourris

In [37]:
nourrir_HU_FFW_gprot_prc

136.35769645716306

### 136.35 % de la population mondiale pourrait être nourris

# Q9

In [38]:
((data['Disponibilité alimentaire (Kcal/personne/jour)']*1000000).sum() / besoin_Kcal)

577606.5287088313

In [39]:
print(" : ", ((data['Disponibilité alimentaire (Kcal/personne/jour)']*1000000).sum() / besoin_Kcal), " : correspond au kcal total pour une personne toute l'année")
nourrir_HU_DA_kcal = ((data['Disponibilité alimentaire (Kcal/personne/jour)']*1000000).sum() / besoin_Kcal)

 :  577606.5287088313  : correspond au kcal total pour une personne toute l'année

In [40]:
nourrir_HU_DA_kcal_prc = (nourrir_HU_DA_kcal / pop_total_2013) * 100
nourrir_HU_DA_kcal_prc

0.00800761934875052

In [41]:
nourrir_HU_DA_kcal_prc * 1000000

8007.619348750521

In [42]:
t = merge['Dispo Alim totale(Kcal)'] * tableau['Ratio(Kcal/Kg)']
t = t.sum() / besoin_Kcal
t

82983911820.56464

In [43]:
(t / pop_total_2013) * 100

1150.4433293279715

### 2eme essai

In [44]:
t2 = merge['Disponibilité alimentaire (Kcal/personne/jour)'] * 1000000 * tableau['Ratio(Kcal/Kg)']
t2.sum() / besoin_Kcal / 1000000000

0.0066148044677678125

In [45]:
t2.sum() / besoin_Kcal / pop_total_2013 *100

0.09170401235371123

### session

In [46]:
merge['Dispo Alim totale(Kcal)'].sum()

5803881866535025.0

In [47]:
nourrir_HU_DA_kcal = merge['Dispo Alim totale(Kcal)'].sum() / besoin_Kcal
nourrir_HU_DA_kcal

6766402642.419149

In [48]:
nourrir_HU_DA_kcal_prc = nourrir_HU_DA_kcal / pop_total_2013 *100
nourrir_HU_DA_kcal_prc

93.80568609913603

In [49]:
nourrir_HU_DA_gprot = merge['Dispo Proteines Totale (g)'].sum() / besoin_gprot
nourrir_HU_DA_gprot

7264832192.124538

In [50]:
nourrir_HU_DA_gprot_prc = nourrir_HU_DA_gprot / pop_total_2013*100
nourrir_HU_DA_gprot_prc

100.71563934210195

### 93% kcal & 100.7% gprot

# Q10

In [51]:
sousAlim_df = pd.read_csv("sousAlim.csv")
sousAlim_df.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,2.6,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,3,Albanie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,0.2,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,4,Algérie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,1.7,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,NR,Non rapportée,NaN

In [52]:
sousAlim_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
Code Domaine              200 non-null object
Domaine                   200 non-null object
Code zone                 200 non-null int64
Zone                      200 non-null object
Code Élément              200 non-null int64
Élément                   200 non-null object
Code Produit              200 non-null int64
Produit                   200 non-null object
Code année                200 non-null int64
Année                     200 non-null object
Unité                     200 non-null object
Valeur                    117 non-null object
Symbole                   200 non-null object
Description du Symbole    200 non-null object
Note                      0 non-null float64
dtypes: float64(1), int64(4), object(10)
memory usage: 23.6+ KB

### chercher comment modifier le type de Valeur , object -> int64

# Q 11

In [53]:
sousAlim_df.dtypes

Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                      object
Unité                      object
Valeur                     object
Symbole                    object
Description du Symbole     object
Note                      float64
dtype: object

In [54]:
sousAlim_df['Valeur'].unique()

array(['7.9', '2.6', '0.2', '1.7', nan, '8.1', '1.6', '1.5', '0.1',
       '26.1', '<0.1', '1', '2.2', '0.5', '0.4', '3.4', '2.8', '0.6',
       '137.7', '4.1', '1.8', '0.3', '4.7', '3.9', '0.7', '1.3', '25.3',
       '2.5', '5.2', '216.3', '22.6', '4.2', '9.1', '0.9', '10', '8.2',
       '3.2', '1.4', '5.3', '7', '6.6', '1.1', '1.9', '13.4', '12.6',
       '2.1', '38.1', '0.8', '14', '2', '1.2', '10.6', '16.4', '3.6',
       '8.3', '2.3', '4.9', '5.6', '10.4', '7.2'], dtype=object)

In [55]:
sousAlim_df['Valeur'] = sousAlim_df.Valeur.str.replace('<', '').astype(float)

In [56]:
sousAlim_df['Valeur'].unique()

array([7.900e+00, 2.600e+00, 2.000e-01, 1.700e+00,       nan, 8.100e+00,
       1.600e+00, 1.500e+00, 1.000e-01, 2.610e+01, 1.000e+00, 2.200e+00,
       5.000e-01, 4.000e-01, 3.400e+00, 2.800e+00, 6.000e-01, 1.377e+02,
       4.100e+00, 1.800e+00, 3.000e-01, 4.700e+00, 3.900e+00, 7.000e-01,
       1.300e+00, 2.530e+01, 2.500e+00, 5.200e+00, 2.163e+02, 2.260e+01,
       4.200e+00, 9.100e+00, 9.000e-01, 1.000e+01, 8.200e+00, 3.200e+00,
       1.400e+00, 5.300e+00, 7.000e+00, 6.600e+00, 1.100e+00, 1.900e+00,
       1.340e+01, 1.260e+01, 2.100e+00, 3.810e+01, 8.000e-01, 1.400e+01,
       2.000e+00, 1.200e+00, 1.060e+01, 1.640e+01, 3.600e+00, 8.300e+00,
       2.300e+00, 4.900e+00, 5.600e+00, 1.040e+01, 7.200e+00])

In [57]:
sousAlim_df.dtypes

Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                      object
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                      float64
dtype: object

In [58]:
sousAlim_df['Valeur'] = sousAlim_df['Valeur'].fillna(0).astype(np.int64)

In [59]:
sousAlim_df.dtypes

Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                      object
Unité                      object
Valeur                      int64
Symbole                    object
Description du Symbole     object
Note                      float64
dtype: object

In [60]:
sousAlim_df.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,2,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,3,Albanie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,0,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,4,Algérie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,1,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,0,NR,Non rapportée,NaN

In [61]:
valeurALim = sousAlim_df.Valeur.unique()

In [62]:
sousAlim_df['Valeur'].sum()

705

In [63]:
(sousAlim_df['Valeur'] * 1000000 / pop_total_2013) * 100

0      0.097044
1      0.027727
2      0.000000
3      0.013863
4      0.000000
         ...
195    0.013863
196    0.138635
197    0.097044
198    0.097044
199    0.083181
Name: Valeur, Length: 200, dtype: float64

In [64]:
pop_total_2013

7213211612.0

In [65]:
(sousAlim_df['Valeur'].sum() * 1000000 / pop_total_2013) * 100

9.773732394418488

### 9,77% est le pourcentage de la population mondiale en sous alimentation

In [66]:
cereals_df = pd.read_csv("cereals.csv")
cereals_df.head()

,Code Domaine,Domaine,Code Pays,Pays,Code Élément,Élément,Code Produit,Produit,Code Année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992,S,Données standardisées
1,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2805,Riz (Eq Blanchi),2013,2013,Milliers de tonnes,461,S,Données standardisées
2,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2513,Orge,2013,2013,Milliers de tonnes,524,S,Données standardisées
3,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2514,Maïs,2013,2013,Milliers de tonnes,313,S,Données standardisées
4,FBS,Bilans Alimentaires,2,Afghanistan,5301,Disponibilité intérieure,2517,Millet,2013,2013,Milliers de tonnes,13,S,Données standardisées

### liste des produits par leur code

In [67]:
cereals = cereals_df['Produit'].unique()

In [68]:
cereals

array(['Blé', 'Riz (Eq Blanchi)', 'Orge', 'Maïs', 'Millet',
       'Céréales, Autres', 'Seigle', 'Avoine', 'Sorgho'], dtype=object)

In [69]:
data['is_cereals'] = data['Produit'].isin(cereals)

### isin() methode qui test une liste

In [70]:
data.head(10)

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
0,Afghanistan,Abats Comestible,animal,0.0,0.0,5.0,1.72,0.20,0.77,5.300000e+07,0.0,0.000000e+00,5.300000e+07,0.0,5.300000e+07,0.0,0.0,0.0,False
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,4.100000e+07,2000000.0,4.000000e+07,3.900000e+07,2000000.0,3.000000e+06,0.0,0.0,0.0,False
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2.000000e+06,0.0,2.000000e+06,2.000000e+06,0.0,0.000000e+00,0.0,0.0,0.0,False
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,8.200000e+07,0.0,8.200000e+07,8.200000e+07,0.0,0.000000e+00,0.0,0.0,0.0,False
5,Afghanistan,"Beurre, Ghee",animal,0.0,0.0,23.0,1.17,2.61,0.03,3.600000e+07,0.0,0.000000e+00,3.600000e+07,0.0,3.600000e+07,0.0,0.0,0.0,False
6,Afghanistan,Bière,vegetal,0.0,0.0,0.0,0.09,0.00,0.00,3.000000e+06,0.0,3.000000e+06,3.000000e+06,0.0,0.000000e+00,0.0,0.0,0.0,False
7,Afghanistan,Blé,vegetal,0.0,0.0,1369.0,160.23,4.69,36.91,5.992000e+09,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,True
8,Afghanistan,Boissons Alcooliques,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False
9,Afghanistan,Café,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False

### correspond au data['is_cereals']

In [71]:
data_cereals = data.loc[data['is_cereals'],:]

In [72]:
data_cereals.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
7,Afghanistan,Blé,vegetal,0.0,0.0,1369.0,160.23,4.69,36.91,5.992000e+09,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,True
12,Afghanistan,"Céréales, Autres",vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
32,Afghanistan,Maïs,vegetal,200000000.0,0.0,21.0,2.50,0.30,0.56,3.130000e+08,0.0,1.000000e+06,7.600000e+07,31000000.0,3.120000e+08,5000000.0,0.0,0.0,True
34,Afghanistan,Millet,vegetal,0.0,0.0,3.0,0.40,0.02,0.08,1.300000e+07,0.0,0.000000e+00,1.200000e+07,1000000.0,1.300000e+07,0.0,0.0,0.0,True
40,Afghanistan,Orge,vegetal,360000000.0,0.0,26.0,2.92,0.24,0.79,5.240000e+08,0.0,1.000000e+07,8.900000e+07,52000000.0,5.140000e+08,22000000.0,0.0,0.0,True

In [73]:
data['Aliments pour animaux'].sum() / (data['Aliments pour animaux'].sum() + data['Nourriture'].sum()) * 100

21.102570454217076

### 21,10% correspond au pourcentage dedié à l'alimentation animal total

In [74]:
alim_animal_crl_prc = data_cereals['Aliments pour animaux'].sum() / (data_cereals['Aliments pour animaux'].sum() + data_cereals['Nourriture'].sum()) * 100

In [75]:
alim_animal_crl_prc

45.91402568664604

### 45,91 % correspond au pourcentage dédié à l'alimentation animal dans les céréals

In [76]:
data.head(10)

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
0,Afghanistan,Abats Comestible,animal,0.0,0.0,5.0,1.72,0.20,0.77,5.300000e+07,0.0,0.000000e+00,5.300000e+07,0.0,5.300000e+07,0.0,0.0,0.0,False
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,4.100000e+07,2000000.0,4.000000e+07,3.900000e+07,2000000.0,3.000000e+06,0.0,0.0,0.0,False
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2.000000e+06,0.0,2.000000e+06,2.000000e+06,0.0,0.000000e+00,0.0,0.0,0.0,False
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,8.200000e+07,0.0,8.200000e+07,8.200000e+07,0.0,0.000000e+00,0.0,0.0,0.0,False
5,Afghanistan,"Beurre, Ghee",animal,0.0,0.0,23.0,1.17,2.61,0.03,3.600000e+07,0.0,0.000000e+00,3.600000e+07,0.0,3.600000e+07,0.0,0.0,0.0,False
6,Afghanistan,Bière,vegetal,0.0,0.0,0.0,0.09,0.00,0.00,3.000000e+06,0.0,3.000000e+06,3.000000e+06,0.0,0.000000e+00,0.0,0.0,0.0,False
7,Afghanistan,Blé,vegetal,0.0,0.0,1369.0,160.23,4.69,36.91,5.992000e+09,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,True
8,Afghanistan,Boissons Alcooliques,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False
9,Afghanistan,Café,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,False

In [77]:
data_cereals

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
7,Afghanistan,Blé,vegetal,0.0,0.0,1369.0,160.23,4.69,36.91,5.992000e+09,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,True
12,Afghanistan,"Céréales, Autres",vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
32,Afghanistan,Maïs,vegetal,200000000.0,0.0,21.0,2.50,0.30,0.56,3.130000e+08,0.0,1.000000e+06,7.600000e+07,31000000.0,3.120000e+08,5000000.0,0.0,0.0,True
34,Afghanistan,Millet,vegetal,0.0,0.0,3.0,0.40,0.02,0.08,1.300000e+07,0.0,0.000000e+00,1.200000e+07,1000000.0,1.300000e+07,0.0,0.0,0.0,True
40,Afghanistan,Orge,vegetal,360000000.0,0.0,26.0,2.92,0.24,0.79,5.240000e+08,0.0,1.000000e+07,8.900000e+07,52000000.0,5.140000e+08,22000000.0,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15545,Îles Salomon,"Céréales, Autres",vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
15568,Îles Salomon,Maïs,vegetal,0.0,0.0,1.0,0.15,0.01,0.03,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
15575,Îles Salomon,Orge,vegetal,0.0,0.0,0.0,0.07,0.00,0.01,1.000000e+06,0.0,1.000000e+06,0.000000e+00,0.0,0.000000e+00,0.0,1000000.0,0.0,True
15591,Îles Salomon,Riz (Eq Blanchi),vegetal,0.0,12000000.0,623.0,63.76,1.36,10.90,4.900000e+07,0.0,4.700000e+07,3.600000e+07,1000000.0,3.000000e+06,0.0,0.0,0.0,True
15593,Îles Salomon,Sorgho,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,NaN,0.0,0.000000e+00,0.0,0.0,0.0,True

In [87]:
sousAlim_df = sousAlim_df.loc[(sousAlim_df[['Valeur']] != 0).all(axis=1)]
sousAlim_df.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,202,Afrique du Sud,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,2,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,4,Algérie,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,1,F,Estimation FAO,NaN
6,FS,Données de la sécurité alimentaire,7,Angola,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,8,F,Estimation FAO,NaN
8,FS,Données de la sécurité alimentaire,194,Arabie saoudite,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,1,F,Estimation FAO,NaN

In [88]:
data.head()

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
0,Afghanistan,Abats Comestible,animal,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0,False
1,Afghanistan,"Agrumes, Autres",vegetal,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,False
2,Afghanistan,Aliments pour enfants,vegetal,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,False
3,Afghanistan,Ananas,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4,Afghanistan,Bananes,vegetal,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,False

In [91]:
sousAlim_zone = sousAlim_df.Zone.unique()

In [103]:
temp = data.loc[data['Pays'].isin(sousAlim_zone)]

### Trie pour chaque produit

In [106]:
temp = temp.groupby('Produit').sum()
temp = temp.reset_index()

In [107]:
temp

,Produit,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
0,Abats Comestible,7000000.0,2.370000e+08,407.0,133.94,12.47,64.69,6.333000e+09,1.960000e+08,8.380000e+08,6.078000e+09,1.600000e+07,5.691000e+09,0.0,0.0,0.0,0.0
1,"Agrumes, Autres",0.0,1.200000e+07,66.0,96.72,0.51,1.23,6.699000e+09,4.800000e+08,2.620000e+08,5.903000e+09,7.810000e+08,6.872000e+09,0.0,70000000.0,46000000.0,0.0
2,"Alcool, non Comestible",0.0,5.872000e+09,0.0,0.00,0.00,0.00,5.844000e+09,1.731000e+09,1.117000e+09,0.000000e+00,0.000000e+00,6.271000e+09,0.0,0.0,185000000.0,0.0
3,Aliments pour enfants,0.0,0.000000e+00,122.0,12.11,0.94,5.09,2.180000e+08,1.520000e+08,3.640000e+08,2.880000e+08,0.000000e+00,0.000000e+00,0.0,0.0,8000000.0,0.0
4,Ananas,0.0,0.000000e+00,258.0,291.83,1.00,2.11,1.350300e+10,3.894000e+09,4.060000e+08,1.211900e+10,1.459000e+09,1.675300e+10,0.0,0.0,238000000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Viande de Suides,0.0,0.000000e+00,2122.0,264.56,198.57,77.19,1.315300e+10,2.220000e+08,1.332000e+09,1.312000e+10,3.900000e+07,1.204900e+10,0.0,0.0,0.0,0.0
94,Viande de Volailles,0.0,9.030000e+08,2714.0,734.70,184.26,246.35,3.276300e+10,1.116000e+09,4.913000e+09,3.155600e+10,3.100000e+08,2.896400e+10,0.0,0.0,2000000.0,0.0
95,"Viande, Autre",4000000.0,1.000000e+06,275.0,86.19,11.54,40.11,2.220000e+09,1.610000e+08,2.200000e+07,2.297000e+09,1.200000e+07,2.353000e+09,0.0,9000000.0,2000000.0,0.0
96,Vin,0.0,3.700000e+07,101.0,54.39,0.00,0.00,2.356000e+09,9.600000e+08,4.300000e+08,1.952000e+09,1.410000e+08,2.831000e+09,0.0,227000000.0,60000000.0,0.0
97,"Épices, Autres",0.0,1.320000e+08,297.0,31.70,9.45,9.40,4.330000e+09,9.180000e+08,7.680000e+08,4.120000e+09,8.600000e+07,4.481000e+09,0.0,0.0,2000000.0,0.0

### Salection des 15 produits les plus exportés

In [116]:
temp_list = temp.sort_values('Exportations - Quantité', ascending = False).head(15)['Produit']
temp_list

39         Huile de Palme
51                 Manioc
79       Riz (Eq Blanchi)
52                   Maïs
83          Sucre Eq Brut
12                    Blé
8                 Bananes
48     Lait - Excl Beurre
49        Légumes, Autres
25         Fruits, Autres
73    Poissons Pelagiques
81                   Soja
41          Huile de Soja
15                   Café
61    Oranges, Mandarines
Name: Produit, dtype: object

In [117]:
temp = data.loc[data['Produit'].isin(temp_list)]

### Selection des 200 plus grandes importations

In [118]:
temp = temp.sort_values('Importations - Quantité', ascending = False).head(200)

In [121]:
temp = temp.groupby('Produit').sum()

In [122]:
temp

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
Produit,,,,,,,,,,,,,,,,
Bananes,0.000000e+00,0.000000e+00,89.0,53.45,0.29,1.10,7.466000e+09,2.204000e+09,9.663000e+09,7.123000e+09,3.440000e+08,7.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.0
Blé,9.871500e+10,1.510700e+10,32177.0,4134.02,140.30,975.56,4.598920e+11,1.065260e+11,1.496290e+11,3.033050e+11,1.616600e+10,4.234230e+11,2.067200e+10,5.975000e+09,-6.639000e+09,45.0
Café,0.000000e+00,0.000000e+00,13.0,11.02,0.00,1.76,1.926000e+09,1.124000e+09,2.986000e+09,1.926000e+09,0.000000e+00,3.000000e+06,0.000000e+00,0.000000e+00,6.100000e+07,0.0
"Fruits, Autres",0.000000e+00,1.200000e+07,278.0,230.37,3.76,3.62,7.316900e+10,6.517000e+09,1.672600e+10,6.721500e+10,4.347000e+09,6.288400e+10,0.000000e+00,1.640000e+09,7.800000e+07,0.0
Huile de Palme,0.000000e+00,1.958900e+10,755.0,32.06,85.37,0.23,2.663900e+10,2.287800e+10,3.076800e+10,6.833000e+09,2.240000e+08,1.944600e+10,0.000000e+00,3.000000e+06,-6.980000e+08,0.0
Huile de Soja,0.000000e+00,9.700000e+09,86.0,3.58,9.75,0.00,1.442600e+10,9.000000e+07,2.266000e+09,4.726000e+09,0.000000e+00,1.228000e+10,0.000000e+00,0.000000e+00,-2.900000e+07,0.0
Lait - Excl Beurre,3.050200e+10,1.265900e+10,6264.0,4522.61,361.74,396.41,3.792630e+11,7.478100e+10,9.046400e+10,3.316840e+11,5.145000e+09,3.619570e+11,0.000000e+00,1.550000e+08,1.629000e+09,0.0
"Légumes, Autres",3.980000e+09,0.000000e+00,734.0,939.21,5.91,34.23,8.710100e+10,1.389500e+10,2.817700e+10,7.571100e+10,7.272000e+09,7.280200e+10,3.000000e+07,1.600000e+08,1.700000e+07,0.0
Manioc,2.514900e+10,2.035500e+10,178.0,62.04,0.36,0.89,6.732600e+10,2.615700e+10,3.465500e+10,1.525700e+10,4.759000e+09,5.876500e+10,0.000000e+00,1.804000e+09,6.300000e+07,0.0
Maïs,4.028850e+11,1.821170e+11,4718.0,591.29,40.41,111.70,7.010680e+11,3.126000e+10,1.024510e+11,5.591800e+10,1.826800e+10,6.752130e+11,3.148000e+09,3.873500e+10,-4.533900e+10,28.0
"Oranges, Mandarines",0.000000e+00,1.000000e+06,175.0,275.78,0.52,2.92,1.953400e+10,9.990000e+09,2.294500e+10,1.919200e+10,3.410000e+08,7.534000e+09,0.000000e+00,0.000000e+00,-9.570000e+08,0.0
Poissons Pelagiques,1.215600e+10,0.000000e+00,115.0,36.08,5.01,15.67,1.609400e+10,4.602000e+09,1.344500e+10,3.937000e+09,0.000000e+00,7.081000e+09,0.000000e+00,0.000000e+00,1.720000e+08,0.0
Riz (Eq Blanchi),1.264400e+10,2.804000e+09,4371.0,440.12,9.55,82.39,1.502340e+11,1.126000e+09,1.399000e+10,1.228320e+11,7.118000e+09,1.429100e+11,4.837000e+09,1.000000e+06,-5.539000e+09,9.0
Soja,1.371000e+10,5.240000e+08,337.0,43.04,14.88,33.02,1.595700e+11,4.126700e+10,9.345500e+10,7.510000e+09,1.777000e+09,1.073880e+11,3.596000e+09,1.324540e+11,-4.000000e+06,0.0
Sucre Eq Brut,0.000000e+00,2.996000e+09,3882.0,397.65,0.00,0.00,7.845300e+10,6.807000e+09,3.420800e+10,6.497100e+10,6.400000e+07,5.569200e+10,0.000000e+00,1.042100e+10,-4.641000e+09,0.0

### Calcul des 2 ratios

In [1]:
temp['ratio1'] = temp['Autres Utilisations'] / temp['Disponibilité intérieure']
temp['ratio2'] = temp['Aliments pour animaux'] / (temp['Aliments pour animaux'] + temp['Nourriture'])

NameError: name 'temp' is not defined

In [124]:
temp

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals,ratio1,ratio2
Produit,,,,,,,,,,,,,,,,,,
Bananes,0.000000e+00,0.000000e+00,89.0,53.45,0.29,1.10,7.466000e+09,2.204000e+09,9.663000e+09,7.123000e+09,3.440000e+08,7.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000,NaN
Blé,9.871500e+10,1.510700e+10,32177.0,4134.02,140.30,975.56,4.598920e+11,1.065260e+11,1.496290e+11,3.033050e+11,1.616600e+10,4.234230e+11,2.067200e+10,5.975000e+09,-6.639000e+09,45.0,0.032849,3.033050e+11
Café,0.000000e+00,0.000000e+00,13.0,11.02,0.00,1.76,1.926000e+09,1.124000e+09,2.986000e+09,1.926000e+09,0.000000e+00,3.000000e+06,0.000000e+00,0.000000e+00,6.100000e+07,0.0,0.000000,NaN
"Fruits, Autres",0.000000e+00,1.200000e+07,278.0,230.37,3.76,3.62,7.316900e+10,6.517000e+09,1.672600e+10,6.721500e+10,4.347000e+09,6.288400e+10,0.000000e+00,1.640000e+09,7.800000e+07,0.0,0.000164,NaN
Huile de Palme,0.000000e+00,1.958900e+10,755.0,32.06,85.37,0.23,2.663900e+10,2.287800e+10,3.076800e+10,6.833000e+09,2.240000e+08,1.944600e+10,0.000000e+00,3.000000e+06,-6.980000e+08,0.0,0.735350,NaN
Huile de Soja,0.000000e+00,9.700000e+09,86.0,3.58,9.75,0.00,1.442600e+10,9.000000e+07,2.266000e+09,4.726000e+09,0.000000e+00,1.228000e+10,0.000000e+00,0.000000e+00,-2.900000e+07,0.0,0.672397,NaN
Lait - Excl Beurre,3.050200e+10,1.265900e+10,6264.0,4522.61,361.74,396.41,3.792630e+11,7.478100e+10,9.046400e+10,3.316840e+11,5.145000e+09,3.619570e+11,0.000000e+00,1.550000e+08,1.629000e+09,0.0,0.033378,3.316840e+11
"Légumes, Autres",3.980000e+09,0.000000e+00,734.0,939.21,5.91,34.23,8.710100e+10,1.389500e+10,2.817700e+10,7.571100e+10,7.272000e+09,7.280200e+10,3.000000e+07,1.600000e+08,1.700000e+07,0.0,0.000000,7.571100e+10
Manioc,2.514900e+10,2.035500e+10,178.0,62.04,0.36,0.89,6.732600e+10,2.615700e+10,3.465500e+10,1.525700e+10,4.759000e+09,5.876500e+10,0.000000e+00,1.804000e+09,6.300000e+07,0.0,0.302335,1.525700e+10
Maïs,4.028850e+11,1.821170e+11,4718.0,591.29,40.41,111.70,7.010680e+11,3.126000e+10,1.024510e+11,5.591800e+10,1.826800e+10,6.752130e+11,3.148000e+09,3.873500e+10,-4.533900e+10,28.0,0.259771,5.591800e+10
"Oranges, Mandarines",0.000000e+00,1.000000e+06,175.0,275.78,0.52,2.92,1.953400e+10,9.990000e+09,2.294500e+10,1.919200e+10,3.410000e+08,7.534000e+09,0.000000e+00,0.000000e+00,-9.570000e+08,0.0,0.000051,NaN
Poissons Pelagiques,1.215600e+10,0.000000e+00,115.0,36.08,5.01,15.67,1.609400e+10,4.602000e+09,1.344500e+10,3.937000e+09,0.000000e+00,7.081000e+09,0.000000e+00,0.000000e+00,1.720000e+08,0.0,0.000000,3.937000e+09
Riz (Eq Blanchi),1.264400e+10,2.804000e+09,4371.0,440.12,9.55,82.39,1.502340e+11,1.126000e+09,1.399000e+10,1.228320e+11,7.118000e+09,1.429100e+11,4.837000e+09,1.000000e+06,-5.539000e+09,9.0,0.018664,1.228320e+11
Soja,1.371000e+10,5.240000e+08,337.0,43.04,14.88,33.02,1.595700e+11,4.126700e+10,9.345500e+10,7.510000e+09,1.777000e+09,1.073880e+11,3.596000e+09,1.324540e+11,-4.000000e+06,0.0,0.003284,7.510000e+09
Sucre Eq Brut,0.000000e+00,2.996000e+09,3882.0,397.65,0.00,0.00,7.845300e+10,6.807000e+09,3.420800e+10,6.497100e+10,6.400000e+07,5.569200e+10,0.000000e+00,1.042100e+10,-4.641000e+09,0.0,0.038188,NaN

# Q12 : 3 Produits pour chacun des 2 ratios

In [125]:
temp.sort_values('ratio1', ascending = False).head(3)

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals,ratio1,ratio2
Produit,,,,,,,,,,,,,,,,,,
Huile de Palme,0.000000e+00,1.958900e+10,755.0,32.06,85.37,0.23,2.663900e+10,2.287800e+10,3.076800e+10,6.833000e+09,2.240000e+08,1.944600e+10,0.0,3.000000e+06,-698000000.0,0.0,0.735350,NaN
Huile de Soja,0.000000e+00,9.700000e+09,86.0,3.58,9.75,0.00,1.442600e+10,9.000000e+07,2.266000e+09,4.726000e+09,0.000000e+00,1.228000e+10,0.0,0.000000e+00,-29000000.0,0.0,0.672397,NaN
Manioc,2.514900e+10,2.035500e+10,178.0,62.04,0.36,0.89,6.732600e+10,2.615700e+10,3.465500e+10,1.525700e+10,4.759000e+09,5.876500e+10,0.0,1.804000e+09,63000000.0,0.0,0.302335,1.525700e+10

In [126]:
temp.sort_values('ratio2', ascending = False).head(3)

,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals,ratio1,ratio2
Produit,,,,,,,,,,,,,,,,,,
Lait - Excl Beurre,3.050200e+10,1.265900e+10,6264.0,4522.61,361.74,396.41,3.792630e+11,7.478100e+10,9.046400e+10,3.316840e+11,5.145000e+09,3.619570e+11,0.000000e+00,1.550000e+08,1.629000e+09,0.0,0.033378,3.316840e+11
Blé,9.871500e+10,1.510700e+10,32177.0,4134.02,140.30,975.56,4.598920e+11,1.065260e+11,1.496290e+11,3.033050e+11,1.616600e+10,4.234230e+11,2.067200e+10,5.975000e+09,-6.639000e+09,45.0,0.032849,3.033050e+11
Riz (Eq Blanchi),1.264400e+10,2.804000e+09,4371.0,440.12,9.55,82.39,1.502340e+11,1.126000e+09,1.399000e+10,1.228320e+11,7.118000e+09,1.429100e+11,4.837000e+09,1.000000e+06,-5.539000e+09,9.0,0.018664,1.228320e+11

# Q13

In [159]:
data_cereals.Produit.unique()

array(['Blé', 'Céréales, Autres', 'Maïs', 'Millet', 'Orge',
       'Riz (Eq Blanchi)', 'Avoine', 'Seigle', 'Sorgho'], dtype=object)

In [133]:
data_cereals

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
7,Afghanistan,Blé,vegetal,0.0,0.0,1369.0,160.23,4.69,36.91,5.992000e+09,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,True
12,Afghanistan,"Céréales, Autres",vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
32,Afghanistan,Maïs,vegetal,200000000.0,0.0,21.0,2.50,0.30,0.56,3.130000e+08,0.0,1.000000e+06,7.600000e+07,31000000.0,3.120000e+08,5000000.0,0.0,0.0,True
34,Afghanistan,Millet,vegetal,0.0,0.0,3.0,0.40,0.02,0.08,1.300000e+07,0.0,0.000000e+00,1.200000e+07,1000000.0,1.300000e+07,0.0,0.0,0.0,True
40,Afghanistan,Orge,vegetal,360000000.0,0.0,26.0,2.92,0.24,0.79,5.240000e+08,0.0,1.000000e+07,8.900000e+07,52000000.0,5.140000e+08,22000000.0,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15545,Îles Salomon,"Céréales, Autres",vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
15568,Îles Salomon,Maïs,vegetal,0.0,0.0,1.0,0.15,0.01,0.03,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,True
15575,Îles Salomon,Orge,vegetal,0.0,0.0,0.0,0.07,0.00,0.01,1.000000e+06,0.0,1.000000e+06,0.000000e+00,0.0,0.000000e+00,0.0,1000000.0,0.0,True
15591,Îles Salomon,Riz (Eq Blanchi),vegetal,0.0,12000000.0,623.0,63.76,1.36,10.90,4.900000e+07,0.0,4.700000e+07,3.600000e+07,1000000.0,3.000000e+06,0.0,0.0,0.0,True
15593,Îles Salomon,Sorgho,vegetal,0.0,0.0,0.0,0.00,0.00,0.00,0.000000e+00,0.0,0.000000e+00,NaN,0.0,0.000000e+00,0.0,0.0,0.0,True

In [141]:
temp = data_cereals.loc[data_cereals['Pays']=='États-Unis d\'Amérique']
temp

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
15347,États-Unis d'Amérique,Avoine,vegetal,1.430000e+09,0.000000e+00,19.0,3.95,0.31,0.79,2.797000e+09,1.020000e+08,1.851000e+09,1.265000e+09,0.0,1.016000e+09,1.030000e+08,0.000000e+00,3.200000e+07,True
15352,États-Unis d'Amérique,Blé,vegetal,6.196000e+09,1.600000e+07,599.0,80.43,2.85,19.35,3.405100e+10,3.469100e+10,5.491000e+09,2.574200e+10,0.0,5.796700e+10,2.096000e+09,0.000000e+00,5.284000e+09,True
15361,États-Unis d'Amérique,"Céréales, Autres",vegetal,7.700000e+07,0.000000e+00,5.0,0.62,0.02,0.15,2.710000e+08,9.100000e+07,2.810000e+08,2.000000e+08,0.0,8.100000e+07,3.000000e+06,0.000000e+00,0.000000e+00,True
15391,États-Unis d'Amérique,Maïs,vegetal,1.280240e+11,1.370230e+11,92.0,12.24,0.26,1.67,2.927760e+11,2.465500e+10,3.595000e+09,3.917000e+09,0.0,3.536990e+11,5.820000e+08,2.323000e+10,-3.986300e+10,True
15393,États-Unis d'Amérique,Millet,vegetal,3.940000e+08,0.000000e+00,0.0,0.00,0.00,0.00,4.160000e+08,2.300000e+07,2.100000e+07,NaN,22000000.0,4.180000e+08,0.000000e+00,0.000000e+00,0.000000e+00,True
15401,États-Unis d'Amérique,Orge,vegetal,1.440000e+09,0.000000e+00,5.0,0.50,0.03,0.14,4.867000e+09,6.960000e+08,8.640000e+08,1.600000e+08,0.0,4.683000e+09,1.070000e+08,3.161000e+09,1.600000e+07,True
15418,États-Unis d'Amérique,Riz (Eq Blanchi),vegetal,0.000000e+00,1.420000e+08,72.0,6.88,0.08,1.33,3.119000e+09,3.522000e+09,9.230000e+08,2.203000e+09,200000000.0,5.745000e+09,1.090000e+08,4.640000e+08,-2.700000e+07,True
15419,États-Unis d'Amérique,Seigle,vegetal,1.840000e+08,0.000000e+00,2.0,0.27,0.01,0.07,3.470000e+08,7.000000e+06,2.350000e+08,8.700000e+07,0.0,1.950000e+08,7.600000e+07,0.000000e+00,-7.600000e+07,True
15421,États-Unis d'Amérique,Sorgho,vegetal,2.351000e+09,0.000000e+00,7.0,0.74,0.07,0.20,4.362000e+09,2.515000e+09,2.160000e+08,2.360000e+08,0.0,9.882000e+09,2.200000e+07,1.753000e+09,-3.220000e+09,True

In [154]:
(temp['Aliments pour animaux'].sum() / 100) * 10

14009600000.0

### 10% de prod Aliment pour animaux USA = 14009600000.0 millier de tones

# Q14

In [164]:
temp = data.loc[data['Pays']=='Thaïlande']
temp

,Pays,Produit,origin,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,is_cereals
13759,Thaïlande,Abats Comestible,animal,0.0,0.0,3.0,1.11,0.09,0.56,74000000.0,5.000000e+06,33000000.0,75000000.0,0.0,4.500000e+07,0.0,0.0,0.0,False
13760,Thaïlande,"Agrumes, Autres",vegetal,0.0,0.0,0.0,0.09,0.00,0.00,8000000.0,6.000000e+06,2000000.0,6000000.0,0.0,1.200000e+07,0.0,2000000.0,0.0,False
13761,Thaïlande,"Alcool, non Comestible",vegetal,0.0,358000000.0,0.0,0.00,0.00,0.00,358000000.0,1.100000e+08,21000000.0,NaN,0.0,4.470000e+08,0.0,0.0,0.0,False
13762,Thaïlande,Aliments pour enfants,vegetal,0.0,0.0,2.0,0.18,0.01,0.08,12000000.0,7.000000e+06,19000000.0,12000000.0,0.0,0.000000e+00,0.0,0.0,0.0,False
13763,Thaïlande,Ananas,vegetal,0.0,0.0,10.0,10.02,0.04,0.08,782000000.0,1.449000e+09,9000000.0,671000000.0,110000000.0,2.209000e+09,0.0,0.0,13000000.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13849,Thaïlande,Viande de Suides,animal,0.0,0.0,124.0,13.00,11.83,3.92,871000000.0,2.200000e+07,1000000.0,871000000.0,0.0,8.910000e+08,0.0,0.0,0.0,False
13850,Thaïlande,Viande de Volailles,animal,0.0,0.0,52.0,13.69,3.62,4.49,945000000.0,5.360000e+08,11000000.0,917000000.0,28000000.0,1.470000e+09,0.0,0.0,0.0,False
13851,Thaïlande,"Viande, Autre",animal,0.0,0.0,0.0,0.03,0.01,0.02,-92000000.0,9.600000e+07,4000000.0,2000000.0,0.0,0.000000e+00,0.0,0.0,0.0,False
13852,Thaïlande,Vin,vegetal,0.0,0.0,0.0,0.12,0.00,0.00,8000000.0,8.000000e+06,16000000.0,8000000.0,0.0,0.000000e+00,0.0,0.0,0.0,False
13853,Thaïlande,"Épices, Autres",vegetal,0.0,0.0,16.0,1.70,0.30,0.43,114000000.0,4.200000e+07,13000000.0,114000000.0,0.0,1.430000e+08,0.0,0.0,0.0,False

In [166]:
temp.loc[temp['Produit']=='Manioc']['Exportations - Quantité']

13809    2.521400e+10
Name: Exportations - Quantité, dtype: float64

In [167]:
temp.loc[temp['Produit']=='Manioc']['Production']

13809    3.022800e+10
Name: Production, dtype: float64

In [169]:
temp.loc[temp['Produit']=='Manioc']['Exportations - Quantité'] / temp.loc[temp['Produit']=='Manioc']['Production'] * 100

13809    83.41273
dtype: float64

### 83,41% de manioc est exporté en thailande

In [174]:
temp = sousAlim_df.loc[sousAlim_df['Zone']=='Thaïlande']
temp

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
182,FS,Données de la sécurité alimentaire,216,Thaïlande,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,5,F,Estimation FAO,NaN

In [175]:
temp['Valeur']

182    5
Name: Valeur, dtype: int64

In [180]:
bpopu_2013_df.loc[bpopu_2013_df['Pays']=='Thaïlande']['Population']

209    68143065.0
Name: Population, dtype: float64

In [183]:
(temp['Valeur'] / bpopu_2013_df.loc[bpopu_2013_df['Pays']=='Thaïlande']['Population']) *100

182   NaN
209   NaN
dtype: float64

In [193]:
sousAlim_thai = sousAlim_df.loc[sousAlim_df['Zone']=='Thaïlande']['Valeur']

In [196]:
sousAlim_thai = sousAlim_thai * 1000000

In [199]:
(sousAlim_thai / 68143065) *100

182    7.337504
Name: Valeur, dtype: float64

### 7.33 % de la population est en sous nutrition en thailande

# Suite : P3_02_CodePythonToSql